function(omega_add_tutorial NAME)
	ExternalProject_Add(
		${NAME}
		URL ""
		SOURCE_DIR ${CMAKE_SOURCE_DIR}/tutorials/${NAME}
		CMAKE_ARGS 
			-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
			-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG}
			-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE}
			-DOMICRON_BINARY_DIR:PATH=${CMAKE_BINARY_DIR}
		INSTALL_COMMAND ""
		)
	set_target_properties(${NAME} PROPERTIES FOLDER "tutorials")
endfunction(omega_add_tutorial NAME)
